name: build and test

on:
  push:
    branches: [ industrial_ci ]
  pull_request:
    branches: [ industrial_ci ]
#   workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *'
#   release:
#     types: [published]

jobs:
  industrial_ci:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rosdistro: [humble]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run industrial_ci
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.rosdistro }}
          ADDITIONAL_DEBS: "ros-${{ matrix.rosdistro }}-diagnostic-updater"
          BEFORE_BUILD: "mkdir -p ros2_ws/src && ln -s $GITHUB_WORKSPACE ros2_ws/src/ros2_topic_sample"
